### ISSUE TITLE
Page not found when I click in the admin sidebar

### ISSUE THREAD

**Issue by Bazimek** [TheBuzzDee/bludit-todo#2]
Page not found when I click in the admin sidebar.

**Comment by TheBuzzDee** [comment]
Hello @Bazimek,

- Do you have an admin-theme installed - if yes, which one ?
- Whats the URL, -shown in browser at the bottom left-  if you hover the "ToDo List" in the admin-sidebar?

**Comment by TheBuzzDee** [comment]
Hello @Bazimek,

Please download and install the current version ([v0.3](https://github.com/TheBuzzDee/bludit-todo/releases/download/0.3/bludit-todo-v0.3.zip)) of the plugin and try again.
Does it still produce the mentioned error? If yes, please answer[ these questions](https://github.com/TheBuzzDee/bludit-todo/issues/2#issuecomment-911364174).
Thanks

**Comment by Bazimek** [comment]
I am using the dark theme admin page.

**Comment by TheBuzzDee** [comment]
Hello @Bazimek, 

> I am using the dark theme admin page.

Do you mean this theme?
https://github.com/tompidev/booty-dark-admin-theme

Could you please tell me whats the URL, -shown in browser at the bottom left- if you hover the "ToDo List" in the admin-sidebar?

Thanks

**Comment by s22-tech** [comment]
I just downloaded ToDo and I'm experiencing the same problem - "Page Not Found" using the Booty Dark admin theme.

The URL you asked for is `www.my-domain.com/admin/plugin/todo`
